export enum AppRoutes {
  Root = 'RootLayout',
  Home = 'Home',
  Attributes = 'Attributes',
  AttributeCreate = 'AttributeCreate',
  AttributeDetails = 'AttributeDetails',
  Brands = 'Brands',
  BrandCreate = 'BrandsCreate',
  BrandDetails = 'BrandDetails',
  Categories = 'Categories',
  CategoryCreate = 'CategoryCreate',
  CategoryDetails = 'CategoryDetails',
  Products = 'Products',
  ProductCreate = 'ProductCreate',
  ProductDetails = 'ProductDetails',
  Warehouses = 'Warehouses',
  WarehouseCreate = 'WarehouseCreate',
  WarehouseDetails = 'WarehouseDetails',
  Staff = 'Staff',
  StaffCreate = 'StaffCreate',
  Orders = 'Orders',
  OrderCreate = 'OrderCreate',
  OrderDetails = 'OrderDetails',
  NotFound = 'NotFound',
  LogIn = 'LogIn',

  Sandbox = 'Sandbox',
  SandboxIcons = 'SandboxIcons',
}
