export { attributesRoutes } from './attributes-routes'
export { brandsRoutes } from './brands-routes'
export { categoriesRoutes } from './categories-routes'
export { productsRoutes } from './products-routes'
export { warehouseRoutes } from './warehouse-routes'
export { staffRoutes } from './staff-routes'
export { ordersRoutes } from './orders-routes'
